import {
  BookOpen,
  Clapperboard,
  KeyRound,
  Library,
  Lightbulb,
  Link2,
  ListChecks,
  Megaphone,
  PenLine,
  ScanSearch,
  SlidersHorizontal,
  Sparkles,
  TrendingUp,
  Wand2,
} from "lucide-react";
import type { FeatureDef } from "./types";

/**
 * ★ Feature Registry — 서비스의 모든 기능 목록 (단일 진실 공급원)
 *
 * 이 배열에서 자동으로 만들어지는 것:
 *  - 채널 허브(2차)의 FeatureCard, 사이드바 하위 메뉴
 *  - 각 기능 페이지의 PageHeader(제목/설명/브레드크럼/상태 배지)
 *  - 메인 화면 채널 카드의 기능 수
 *
 * 기능을 추가하거나 바꾸면 docs/FEATURE_REGISTRY.md 도 함께 갱신한다.
 */
export const FEATURES: FeatureDef[] = [
  // ───────── YouTube ─────────
  {
    id: "yt-trends",
    channelId: "youtube",
    order: 1,
    title: "YouTube 트렌드 찾기",
    description: "최근 7일 / 14일 / 21일 데이터를 기준으로 잘되는 영상, 주제, 키워드를 찾습니다.",
    href: "/youtube/trends",
    icon: TrendingUp,
    kind: "trend",
    status: "mock",
    requiredProviders: ["youtube"],
    inputs: ["카테고리", "검색 키워드", "기간(7/14/21일)", "Shorts/일반", "정렬"],
    outputs: ["썸네일", "제목", "채널", "게시일", "조회수", "일평균 조회수", "주요 키워드", "Trend Score"],
    tags: ["YouTube Data API"],
  },
  {
    id: "yt-product-video",
    channelId: "youtube",
    order: 2,
    title: "제품 홍보 영상 만들기",
    description: "제품 라이브러리의 제품과 트렌드를 조합해 홍보 영상 원고를 만듭니다.",
    href: "/youtube/product-video",
    icon: Clapperboard,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["제품", "참고 트렌드", "주요 키워드", "참고 영상", "영상 길이", "콘텐츠 스타일"],
    outputs: ["추천 제목 5개", "Hook", "대본", "설명글", "주요 키워드", "해시태그"],
    tags: ["제품 라이브러리"],
  },
  {
    id: "yt-info-video",
    channelId: "youtube",
    order: 3,
    title: "정보성 영상 만들기",
    description: "제품과 관계없는 정보성 영상의 주제, 제목, 대본을 만듭니다.",
    href: "/youtube/info-video",
    icon: Lightbulb,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["카테고리", "주제", "트렌드", "주요 키워드", "영상 길이"],
    outputs: ["추천 주제", "제목", "Hook", "대본", "설명글", "키워드"],
  },

  // ───────── NAVER Clip ─────────
  {
    id: "clip-trends",
    channelId: "naver-clip",
    order: 1,
    title: "네이버 트렌드 소재 찾기",
    description: "네이버 검색·쇼핑 데이터로 급상승 주제와 키워드, 시즌 소재를 찾습니다.",
    href: "/naver-clip/trends",
    icon: ScanSearch,
    kind: "trend",
    status: "mock",
    requiredProviders: ["naver"],
    inputs: ["카테고리", "검색어", "최근 기간"],
    outputs: ["급상승 주제", "급상승 키워드", "시즌 키워드", "관련 키워드"],
    tags: ["NAVER DataLab"],
  },
  {
    id: "clip-product-content",
    channelId: "naver-clip",
    order: 2,
    title: "제품 홍보 클립 만들기",
    description: "저장된 제품 정보로 짧고 강한 클립 대본을 만듭니다.",
    href: "/naver-clip/product-content",
    icon: Megaphone,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["제품", "트렌드", "주요 키워드", "콘텐츠 스타일"],
    outputs: ["제목", "Hook", "클립 대본", "설명글", "키워드", "해시태그"],
    tags: ["제품 라이브러리"],
  },
  {
    id: "clip-info-content",
    channelId: "naver-clip",
    order: 3,
    title: "정보성 클립 만들기",
    description: "현재 트렌드와 키워드로 정보형 클립 원고를 만듭니다.",
    href: "/naver-clip/info-content",
    icon: Sparkles,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["카테고리", "현재 트렌드", "키워드"],
    outputs: ["추천 주제", "제목", "대본", "설명글", "키워드"],
  },

  // ───────── NAVER Blog ─────────
  {
    id: "blog-trends",
    channelId: "naver-blog",
    order: 1,
    title: "네이버 트렌드·키워드 찾기",
    description: "검색 추이, 관련 검색어, 급상승·시즌 키워드와 글감 아이디어를 찾습니다.",
    href: "/naver-blog/trends",
    icon: ScanSearch,
    kind: "trend",
    status: "mock",
    requiredProviders: ["naver"],
    inputs: ["검색어", "카테고리", "최근 기간"],
    outputs: ["관련 검색어", "최근 검색 추이", "급상승 키워드", "시즌 키워드", "콘텐츠 아이디어"],
    tags: ["NAVER DataLab", "검색 API"],
  },
  {
    id: "blog-product-writing",
    channelId: "naver-blog",
    order: 2,
    title: "제품 블로그 글 만들기",
    description: "제품 정보와 키워드로 블로그 글을 만듭니다. 경험하지 않은 사용 후기는 쓰지 않습니다.",
    href: "/naver-blog/product-writing",
    icon: PenLine,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["제품", "메인 키워드", "서브 키워드", "글 스타일", "글 길이", "실제 경험(선택)"],
    outputs: ["제목 후보", "전체 본문", "소제목", "제품 장점", "정보", "CTA", "키워드", "해시태그"],
    tags: ["제품 라이브러리", "정직성 가드레일"],
  },
  {
    id: "blog-info-writing",
    channelId: "naver-blog",
    order: 3,
    title: "정보·트렌드 글 만들기",
    description: "제품 없이 일반 정보, 트렌드, IT, AI, 생활정보 글을 만듭니다.",
    href: "/naver-blog/info-writing",
    icon: BookOpen,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["글 유형", "주제", "트렌드", "메인 키워드", "글 길이"],
    outputs: ["제목 후보", "전체 본문", "소제목", "키워드", "해시태그"],
  },
  {
    id: "blog-auto-writing",
    channelId: "naver-blog",
    order: 4,
    title: "자동 글쓰기",
    description: "주제만 넣으면 저장된 스타일과 데이터를 바탕으로 전체 글을 완성합니다.",
    href: "/naver-blog/auto-writing",
    icon: Wand2,
    kind: "generator",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["주제", "글 유형", "제품(선택)"],
    outputs: ["제목 후보", "전체 본문", "키워드", "해시태그"],
    tags: ["AI Memory 활용"],
  },

  // ───────── 공통 도구 ─────────
  {
    id: "product-learning",
    channelId: "tools",
    order: 1,
    title: "제품 상세페이지 학습",
    description: "쿠팡, 스마트스토어 상세페이지를 분석해 구조화된 제품 데이터로 저장합니다.",
    href: "/tools/product-learning",
    icon: ListChecks,
    kind: "tool",
    status: "mock",
    requiredProviders: ["openai"],
    inputs: ["상품 URL / 상세 이미지 / 텍스트"],
    outputs: ["기본 정보", "AI 제품 요약", "콘텐츠 제작용 데이터"],
    tags: ["Collector → Analyzer"],
  },
  {
    id: "product-library",
    channelId: "tools",
    order: 2,
    title: "제품 라이브러리",
    description: "분석한 제품을 저장하고, 콘텐츠 생성에 반복해서 재사용합니다.",
    href: "/tools/product-library",
    icon: Library,
    kind: "tool",
    status: "mock",
    requiredProviders: [],
    inputs: ["검색어", "카테고리"],
    outputs: ["제품 카드/목록", "제품 상세 분석 데이터"],
  },
  {
    id: "video-import",
    channelId: "tools",
    order: 3,
    title: "영상 URL 가져오기",
    description: "참고 영상 URL을 등록해 제목, 채널, 길이를 저장하고 영상 제작에 활용합니다.",
    href: "/tools/video-import",
    icon: Link2,
    kind: "tool",
    status: "mock",
    requiredProviders: ["youtube"],
    inputs: ["영상 URL", "메모"],
    outputs: ["영상 메타데이터", "참고 영상 목록"],
  },

  // ───────── 설정 ─────────
  {
    id: "api-center",
    channelId: "settings",
    order: 1,
    title: "API 연결 센터",
    description: "OpenAI, YouTube Data API, NAVER API를 연결하고 상태를 확인합니다.",
    href: "/settings/api",
    icon: KeyRound,
    kind: "settings",
    status: "mock",
    requiredProviders: [],
    inputs: ["API Key", "Client ID / Secret"],
    outputs: ["연결 상태", "테스트 결과"],
  },
  {
    id: "general-settings",
    channelId: "settings",
    order: 2,
    title: "일반 설정",
    description: "계정, 기본 채널, 생성 기본값 등을 설정합니다.",
    href: "/settings",
    icon: SlidersHorizontal,
    kind: "settings",
    status: "planned",
    requiredProviders: [],
    inputs: [],
    outputs: [],
  },
];
