import {
  BookOpen,
  Clapperboard,
  KeyRound,
  Library,
  Lightbulb,
  Link2,
  ListChecks,
  ShieldCheck,
  Megaphone,
  PenLine,
  ScanSearch,
  ScrollText,
  Sparkles,
  TrendingUp,
  UserCheck,
  Users,
  Wand2,
} from "lucide-react";
import type { MemberTier } from "@/lib/types";
import type { FeatureDef } from "./types";

/* 기본 접근 등급 묶음 (관리자는 항상 전체 접근) */
const ALL: MemberTier[] = ["silver", "gold", "vip"];
const GOLD_UP: MemberTier[] = ["gold", "vip"];
const VIP_ONLY: MemberTier[] = ["vip"];

/**
 * ★ Feature Registry — 서비스의 모든 기능 목록 (단일 진실 공급원)
 *
 * 이 배열에서 자동으로 만들어지는 것:
 *  - 채널 허브(2차)의 FeatureCard, 사이드바 하위 메뉴
 *  - 각 기능 페이지의 PageHeader(제목/설명/브레드크럼/상태 배지)
 *  - 메인 화면 채널 카드의 기능 수
 *
 * 기능을 추가하거나 바꾸면 docs/FEATURE_REGISTRY.md 도 함께 갱신한다.
 */
export const FEATURES: FeatureDef[] = [
  // ───────── YouTube ─────────
  {
    id: "yt-trends",
    channelId: "youtube",
    order: 1,
    title: "YouTube 트렌드 찾기",
    description: "국가·카테고리·게시일·구독자·조회수 조건으로 잘되는 영상을 찾고, 추천 키워드·주제와 잘된 이유를 확인합니다.",
    href: "/youtube/trends",
    icon: TrendingUp,
    kind: "trend",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["youtube"],
    inputs: ["국가", "카테고리", "검색 키워드", "게시일 범위", "구독자·조회수·댓글 범위", "Shorts/롱폼", "저장한 조건"],
    outputs: ["Shorts/롱폼", "키워드·태그", "정렬(Trend Score·조회수·게시일·일평균)", "추천 키워드", "AI 추천 주제", "잘된 이유·추천 제목", "찜", "50개씩 더 불러오기"],
    tags: ["YouTube Data API"],
  },
  {
    id: "yt-product-video",
    channelId: "youtube",
    order: 2,
    title: "제품 홍보 영상 만들기",
    description: "제품 라이브러리의 제품과 트렌드를 조합해 홍보 영상 원고를 만듭니다.",
    href: "/youtube/product-video",
    icon: Clapperboard,
    kind: "generator",
    status: "live",
    defaultTiers: GOLD_UP,
    requiredProviders: ["openai"],
    inputs: ["제품", "참고 트렌드", "주요 키워드", "참고 영상", "영상 길이", "콘텐츠 스타일"],
    outputs: ["추천 제목 5개", "Hook", "대본", "설명글", "주요 키워드", "해시태그"],
    tags: ["제품 라이브러리"],
  },
  {
    id: "yt-info-video",
    channelId: "youtube",
    order: 3,
    title: "정보성 영상 만들기",
    description: "제품과 관계없는 정보성 영상의 주제, 제목, 대본을 만듭니다.",
    href: "/youtube/info-video",
    icon: Lightbulb,
    kind: "generator",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["openai"],
    inputs: ["카테고리", "주제", "트렌드", "주요 키워드", "영상 길이"],
    outputs: ["추천 주제", "제목", "Hook", "대본", "설명글", "키워드"],
  },

  // ───────── NAVER 클립 ─────────
  {
    id: "clip-trends",
    channelId: "naver-clip",
    order: 1,
    title: "네이버 트렌드 소재 찾기",
    description: "콘텐츠 프로필 범위 안에서 네이버 검색 데이터로 급상승 소재와 키워드, 시즌 소재를 찾습니다.",
    href: "/naver-clip/trends",
    icon: ScanSearch,
    kind: "trend",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["naver"],
    inputs: ["콘텐츠 프로필(자동)", "검색어", "기간(7일~3년)"],
    outputs: ["급상승 주제", "급상승 키워드", "시즌 키워드", "관련 키워드"],
    tags: ["NAVER DataLab"],
  },
  {
    id: "clip-product-content",
    channelId: "naver-clip",
    order: 2,
    title: "제품 홍보 클립 만들기",
    description: "저장된 제품 정보로 짧고 강한 클립 대본을 만듭니다.",
    href: "/naver-clip/product-content",
    icon: Megaphone,
    kind: "generator",
    status: "live",
    defaultTiers: GOLD_UP,
    requiredProviders: ["openai"],
    inputs: ["제품", "트렌드", "주요 키워드", "콘텐츠 스타일"],
    outputs: ["제목", "Hook", "클립 대본", "설명글", "키워드", "해시태그"],
    tags: ["제품 라이브러리"],
  },
  {
    id: "clip-info-content",
    channelId: "naver-clip",
    order: 3,
    title: "정보성 클립 만들기",
    description: "현재 트렌드와 키워드로 정보형 클립 원고를 만듭니다.",
    href: "/naver-clip/info-content",
    icon: Sparkles,
    kind: "generator",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["openai"],
    inputs: ["카테고리", "현재 트렌드", "키워드"],
    outputs: ["추천 주제", "제목", "대본", "설명글", "키워드"],
  },

  // ───────── NAVER 블로그 ─────────
  {
    id: "blog-trends",
    channelId: "naver-blog",
    order: 1,
    title: "네이버 트렌드·키워드 찾기",
    description: "콘텐츠 프로필 범위 안에서 검색 추이, 검색량, 관련 검색어, 급상승·시즌 키워드와 글감 아이디어를 찾습니다.",
    href: "/naver-blog/trends",
    icon: ScanSearch,
    kind: "trend",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["naver"],
    inputs: ["콘텐츠 프로필(자동)", "검색어", "기간(7일~3년)"],
    outputs: ["월간 검색량", "블로그 문서 수", "관련 검색어", "검색 추이", "급상승 키워드", "시즌 키워드", "글감 아이디어"],
    tags: ["NAVER DataLab", "검색 API"],
  },
  {
    id: "blog-product-writing",
    channelId: "naver-blog",
    order: 2,
    title: "제품 블로그 글 만들기",
    description: "제품 정보와 키워드로 블로그 글을 만듭니다. 경험하지 않은 사용 후기는 쓰지 않습니다.",
    href: "/naver-blog/product-writing",
    icon: PenLine,
    kind: "generator",
    status: "live",
    defaultTiers: GOLD_UP,
    requiredProviders: ["openai"],
    inputs: ["제품", "메인 키워드", "서브 키워드", "글 스타일", "글 길이", "실제 경험(선택)"],
    outputs: ["제목 후보", "전체 본문", "소제목", "제품 장점", "정보", "CTA", "키워드", "해시태그"],
    tags: ["제품 라이브러리", "정직성 가드레일"],
  },
  {
    id: "blog-info-writing",
    channelId: "naver-blog",
    order: 3,
    title: "정보·트렌드 글 만들기",
    description: "제품 없이 일반 정보, 트렌드, IT, AI, 생활정보 글을 만듭니다.",
    href: "/naver-blog/info-writing",
    icon: BookOpen,
    kind: "generator",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["openai"],
    inputs: ["글 유형", "주제", "트렌드", "메인 키워드", "글 길이"],
    outputs: ["제목 후보", "전체 본문", "소제목", "키워드", "해시태그"],
  },
  {
    id: "blog-auto-writing",
    channelId: "naver-blog",
    order: 4,
    title: "자동 글쓰기",
    description: "주제만 넣으면 저장된 스타일과 데이터를 바탕으로 전체 글을 완성합니다.",
    href: "/naver-blog/auto-writing",
    icon: Wand2,
    kind: "generator",
    status: "live",
    defaultTiers: VIP_ONLY,
    requiredProviders: ["openai"],
    inputs: ["주제", "글 유형", "제품(선택)"],
    outputs: ["제목 후보", "전체 본문", "키워드", "해시태그"],
    tags: ["AI Memory 활용"],
  },

  // ───────── 공통 도구 ─────────
  {
    id: "product-learning",
    channelId: "tools",
    order: 1,
    title: "제품 상세페이지 학습",
    description: "상품 URL 또는 상세페이지 이미지를 AI 가 읽고 분석해 구조화된 제품 데이터로 저장합니다.",
    href: "/tools/product-learning",
    icon: ListChecks,
    kind: "tool",
    status: "live",
    defaultTiers: GOLD_UP,
    requiredProviders: ["openai"],
    inputs: ["상품 URL / 상세 이미지 / 텍스트"],
    outputs: ["기본 정보", "AI 제품 요약", "콘텐츠 제작용 데이터"],
    tags: ["Collector → Analyzer"],
  },
  {
    id: "product-library",
    channelId: "tools",
    order: 2,
    title: "제품 라이브러리",
    description: "분석한 제품을 저장하고, 콘텐츠 생성에 반복해서 재사용합니다.",
    href: "/tools/product-library",
    icon: Library,
    kind: "tool",
    status: "live",
    defaultTiers: GOLD_UP,
    requiredProviders: [],
    inputs: ["검색어", "카테고리"],
    outputs: ["제품 카드/목록", "제품 상세 분석 데이터"],
  },
  {
    id: "video-import",
    channelId: "tools",
    order: 3,
    title: "영상 URL 가져오기",
    description: "샤오홍슈·YouTube 영상 링크를 여러 개 한 번에 등록합니다. 샤오홍슈 영상은 워터마크 없는 원본을 소리 없이 저장하고, 자막·글자 로고를 자동으로 흐리게 할 수 있습니다.",
    href: "/tools/video-import",
    icon: Link2,
    kind: "tool",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: ["youtube"],
    inputs: ["영상 URL 여러 개(줄바꿈)", "메모"],
    outputs: ["영상 메타데이터", "참고 영상 목록", "샤오홍슈: 소리 없는 mp4 바로 저장·ZIP", "YouTube: 다운로드 명령(yt-dlp)"],
  },

  // ───────── 설정 ─────────
  {
    id: "api-center",
    channelId: "settings",
    order: 1,
    title: "API 연결 센터",
    description: "OpenAI, YouTube Data API, NAVER API를 연결하고 상태를 확인합니다.",
    href: "/settings/api",
    icon: KeyRound,
    kind: "settings",
    status: "live",
    defaultTiers: ALL,
    requiredProviders: [],
    inputs: ["API Key", "Client ID / Secret"],
    outputs: ["연결 상태", "테스트 결과"],
  },
  // ───────── 사이트 관리 (관리자 전용) ─────────
  {
    id: "admin-approvals",
    channelId: "admin",
    order: 1,
    title: "가입 승인",
    description: "회원가입 신청을 확인하고 등급을 정해 승인하거나 거절합니다.",
    href: "/admin/approvals",
    icon: UserCheck,
    kind: "admin",
    status: "live",
    defaultTiers: [],
    adminOnly: true,
    requiredProviders: [],
    inputs: ["승인 등급", "거절 사유"],
    outputs: ["승인 대기 목록"],
  },
  {
    id: "admin-users",
    channelId: "admin",
    order: 2,
    title: "사용자 관리",
    description: "승인된 사용자 목록을 보고 역할(관리자 / 실버 / 골드 / VIP)을 변경합니다.",
    href: "/admin/users",
    icon: Users,
    kind: "admin",
    status: "live",
    defaultTiers: [],
    adminOnly: true,
    requiredProviders: [],
    inputs: ["역할"],
    outputs: ["사용자 목록"],
  },
  {
    id: "admin-permissions",
    channelId: "admin",
    order: 3,
    title: "권한 관리",
    description: "등급(실버 / 골드 / VIP)별로 접근할 수 있는 메뉴와 기능을 정합니다.",
    href: "/admin/permissions",
    icon: ShieldCheck,
    kind: "admin",
    status: "live",
    defaultTiers: [],
    adminOnly: true,
    requiredProviders: [],
    inputs: ["등급별 허용 여부"],
    outputs: ["권한표"],
  },
  {
    id: "admin-audit-logs",
    channelId: "admin",
    order: 4,
    title: "활동 기록",
    description: "가입 승인, 등급·권한 변경, 로그인, 탈퇴 등 주요 활동을 시간순으로 확인합니다.",
    href: "/admin/audit-logs",
    icon: ScrollText,
    kind: "admin",
    status: "live",
    defaultTiers: [],
    adminOnly: true,
    requiredProviders: [],
    inputs: ["검색", "종류 필터"],
    outputs: ["활동 기록"],
  },
];
